
version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:
    build:
        working_directory: ~/circleci-starter
        docker:
            - image: cimg/base:2022.09
            - image: cimg/node:14.15.0 # Primary execution image
        steps:
            - checkout
            - setup_remote_docker:
                version: 20.10.14
            - run:
                name: build
                command: |
                    # Build
                      echo '_____________beginning build'
                      docker build -t udagram-api-feed:dev1 ./udagram-api-feed
                      docker build -t udagram-api-user:dev1 ./udagram-api-user
                      docker build -t udagram-frontend:dev2 ./udagram-frontend
                      docker build -t reverseproxy:dev1 ./udagram-reverseproxy  

                      # Tagging
                      echo '_____________beginning tag'
                      docker tag udagram-api-feed:dev1 frankie08/udagram-api-feed:dev1
                      docker tag udagram-api-user:dev1 frankie08/udagram-api-user:dev1
                      docker tag udagram-frontend:dev2 frankie08/udagram-frontend:dev2
                      docker tag reverseproxy:dev1 frankie08/reverseproxy:dev1

                      echo 'DOCKER IMAGE LS____'
                      docker image ls

            - run:
                name: after_success
                command: |
                    # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
                    # Login Docker  
                    echo '________LOGIN_______'
                    #- docker login -u=username -p=password
                    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
                    #- echo 'username, password'  $DOCKER_USERNAME $DOCKER_PASSWORD
                    # Pushing 
                    echo '_____________beginning push image'
                    docker push frankie08/udagram-api-feed:dev1
                    docker push frankie08/udagram-api-user:dev1
                    docker push frankie08/udagram-frontend:dev2
                    docker push frankie08/reverseproxy:dev1
          